version: '3'

services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    container_name: todo_app
    volumes:
      - ./:/var/www/html
    depends_on:
      - pgsql
    networks:
      - todo

  nginx:
    image: nginx:1.21
    container_name: todo_nginx
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "${NGINX_PORT:-8080}:80"
    depends_on:
      - app
    networks:
      - todo

  pgsql:
    image: postgres:13.3
    container_name: todo_postgres
    command: [
      "postgres",
      "-c", "max_connections=50",
      "-c", "shared_buffers=512MB",
      "-c", "effective_cache_size=512MB",
      "-c", "work_mem=16MB",
      "-c", "maintenance_work_mem=512MB",
      "-c", "random_page_cost=1.1",
      "-c", "temp_file_limit=512MB",
      "-c", "log_min_duration_statement=200ms",
      "-c", "idle_in_transaction_session_timeout=10s",
      "-c", "lock_timeout=1s",
      "-c", "statement_timeout=60s",
      "-c", "shared_preload_libraries=pg_stat_statements",
      "-c", "pg_stat_statements.max=10000",
      "-c", "pg_stat_statements.track=all"
    ]
    environment:
      POSTGRES_DB: ${DB_DATABASE:-todo}
      POSTGRES_USER: ${DB_USERNAME:-user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 200MB
    networks:
      - todo

networks:
  todo:

volumes:
  pgdata:
